### PR TITLE
Improving route from string to array

### PR DESCRIPTION
**Pull request by carlosdaniel26**

### CODE REVIEW

**Comment by carlosdaniel26** [comment]
Okay i think its done.

**Comment by FabioAugustoRodrigues** [comment]
are you still going to create something here? because otherwise I will do the tokenization logic

**Comment by carlosdaniel26** [comment]
I dont know what are you talking about, i think that the tokenization logic is done, right?

**Comment by FabioAugustoRodrigues** [comment]
you created the tokenizeRoute function but it is not used
i thought you would use it on registered routes or something else

and now i realized that has something missing here haha we need to make routes have parameters
i'll write the code and you see if everything is ok

**Comment by carlosdaniel26** [comment]
Yeah, you're right haha i forgot the mainly part.

**Comment by carlosdaniel26** [comment]
Every implementation I think of seems too complex

**Comment by FabioAugustoRodrigues** [comment]
In ControllerRoutes we use regular expressions to define patterns that in the defined routes.
These patterns help us extract values from routes.


In other words, we store the route with the defaults defined here:
```php
private static function transformRouteToRegex($route)
{
     $route = preg_replace(self::PARAM_PATTERN, '([^\/]+)', $route);
     $route = '#^' . $route . '$#';

     return $route;
}
```


And in run method, we just check if the route the user passed matches any pattern here:
```php
public static function run($request_data, $route, $request_method)
{
     foreach (self::$routes[$request_method] as $routePattern => $methodObj) {
         if (preg_match($routePattern, $route, $matches)) {
         
         // ...
```


<br><br>

What do you think of this approach? Now it's necessary to pass values to templates, but it's better in another pl

**Comment by FabioAugustoRodrigues** [comment]
I'm going to close this PR, if you want to add more details, open another one.

**Pull request merged**
