### PR TITLE
Creating a route system to iMono.

### PR DESCRIPTION
**Pull request by carlosdaniel26**
its not finished but already have a lot of things done.
 
 Im open to any opinion about it.

### CODE REVIEW

**Comment by carlosdaniel26** [comment]
okay now i just have a bug that i still dont know where to solve, the views are being called as json when response.

**Comment by carlosdaniel26** [comment]
for some reason the github had some bug and another account with my name is here

**Comment by FabioAugustoRodrigues** [comment]
i thought this PR was good and now i'm going to make some updates and you can check it out.

need to update the htaccess file to redirect each request uri to index.php
and i think it's interesting to put the routes declared by the developer in another file

**Comment by FabioAugustoRodrigues** [comment]
currently the header of all responses is content-type application/json, but we have a problem with this: the index.php method of ExampleController returns HTML, so the header cannot be json.

we will probably have to change the header according to the request. What do you think?

**Comment by carlosdaniel26** [comment]
Yes, we need to change this, maybe some method like response()->json() or something else.

I have a question, why still use the htacess file since we already have a route system?

**Comment by FabioAugustoRodrigues** [comment]
this change you made worked great, but i'm going to change the code so the example page works, ok?

i still use the htaccess file to redirect all requests to index.php, so the index.php file is the application input

**Comment by carlosdaniel26** [comment]
Actually the json() function was just a quick update, i'll transform this in something better like use paramters in the function or smt like this

**Comment by carlosdaniel26** [comment]
okay its done i think, just need some updates.

I still dont like this:


```
public function getCurrentDateTime() {

        self::json();
        
        return $this->respondsWithData(
            [
                "data" => [
                    "current_date_time" => date('Y-m-d H:i:s')
                ],
                "message" => ""
            ],
            200
        );
    }
    ```
    
the  " self::json();"
dont seems right use this way

**Comment by carlosdaniel26** [comment]
and about it:

`ControllerRoutes::get("/", "app\\controller\\http\\API\\ExampleController", "index");`

i dont think need to put all the path as string is a good way, maybe we can forgot about the path string and use like in laravel.

Import the class in the beggin of the file and then use smt like:

`ControllerRoutes::get("/", [ExampleController::class, 'index']);`

what you think about it?

**Comment by FabioAugustoRodrigues** [comment]
> okay its done i think, just need some updates.
> 
> I still dont like this:
> 
> ```
> public function getCurrentDateTime() {
> 
>         self::json();
>         
>         return $this->respondsWithData(
>             [
>                 "data" => [
>                     "current_date_time" => date('Y-m-d H:i:s')
>                 ],
>                 "message" => ""
>             ],
>             200
>         );
>     }
>     ```
>     
> the  " self::json();"
> dont seems right use this way
> ```

yes, it's not very conventional to mention the header at the beginning of the method, the ideal is to specify it during the response, that's why i thought of an approach of specifying the header when the return is made.
i remember that the spring framework has something similiar.

first we need to create a response class to abstract the content, in this class i created the headers array

- Response.php
```php
<?php

namespace app\controller\http;

use app\util\PayloadHttp;

class Response
{
    private $data;
    private $status;
    private $headers = [];

    public function __construct($data = null, int $status = 200)
    {
        $this->data = $data;
        $this->status = $status;
    }

    public function withHeader(string $header)
    {
        $this->headers[] = $header;
        return $this;
    }

    public function send()
    {
        $payload = new PayloadHttp($this->status, $this->data);

        foreach ($this->headers as $header) {
            header($header);
        }

        http_response_code($payload->getStatus());
        
        echo json_encode($payload);
    }
}
```
<br>

in the ControllerAbstract class we will use a method called "createResponse" and return the Response class, and we already have methods that specify the header
- CotrollerAbstract.php

```php
<?php

namespace app\controller\http;

abstract class ControllerAbstract
{
    public function __construct()
    {
    }

    protected function createResponse($data = null, int $status = 200)
    {
        return new Response($data, $status);
    }

    protected function respond($data = null, int $status)
    {
        return $this->createResponse($data, $status)->send();
    }

    protected function respondJson($data = null, int $status)
    {
        return $this->createResponse($data, $status)->withHeader("Content-Type: application:json")->send();
    }

    protected function formatJson(string $json)
    {
        $json = preg_replace('/,/', '$0 ', $json);

        return $json;
    }
}
```
<br>
<br>

so the example method in controller could be look this:

```php
...
public function getCurrentDateTime()
    {
        return $this->respondJson(
            [
                "data" => [
                    "current_date_time" => date('Y-m-d H:i:s')
                ],
                "message" => ""
            ],
            200
        );
    }
```

<br><br><br>


what you think about it?

**Comment by FabioAugustoRodrigues** [comment]
> and about it:
> 
> `ControllerRoutes::get("/", "app\\controller\\http\\API\\ExampleController", "index");`
> 
> i dont think need to put all the path as string is a good way, maybe we can forgot about the path string and use like in laravel.
> 
> Import the class in the beggin of the file and then use smt like:
> 
> `ControllerRoutes::get("/", [ExampleController::class, 'index']);`
> 
> what you think about it?

We can use the ::class constant, it returns the full name of the class.
So the routes could be like this:
<br>

```php
<?php

namespace app\routes;

use app\controller\http\API\ExampleController;
use app\controller\http\ControllerRoutes;

ControllerRoutes::get("/", ExampleController::class, "index");
ControllerRoutes::post("/api/getCurrentDateTime", ExampleController::class, "getCurrentDateTime");
```

**Comment by FabioAugustoRodrigues** [comment]
and I loved the separation of the controller routes, it was something I should have already done

**Comment by carlosdaniel26** [comment]
Great updates, and about the separation it was the first thing i saw when i looked at iMono.

**Comment by carlosdaniel26** [comment]
We still need to solve this, but lets solve it in another PR.

```php
require('./app/views/index.html');
```

**Comment by carlosdaniel26** [comment]
Lets finish the use of ::class before

**Comment by FabioAugustoRodrigues** [comment]
now, i think it's almost finished, but i've seen a problem

we have this example endpoint:
```php
ControllerRoutes::post("/api/getCurrentDateTime", ExampleController::class, "getCurrentDateTime");
```

but if you call ```/api/getCurrentDateTime/``` in your application, it wont work, because of the last ```/```
probably we need to break the url into an array and check the routes, instead of a string, i don't know
but anyway we can do this in another PR, what do you think

**Comment by carlosdaniel26** [comment]
yeah, i think the basics are finished, lets make another PR and solve it

**Pull request merged**
